```{r}
library(nycflights13)
library(tidyverse)
```

```{r}
devtools::install_github("privefl/advr38pkg")

monte_carlo <- function(N) {
  
  hits <- 0
  for (i in seq_len(N)) {
    u1 <- runif(1)
    u2 <- runif(1)
    if (u1 ^ 2 > u2) {
      hits <- hits + 1
    }
  }
  
  hits / N
}
```

```{r}
base::subset(flights,)
```
```{r}
filter(flights, month == 11 | month == 12)
```

```{r}
df <- tibble(x = c(1, NA, 3))
filter(df, x > 1)
filter(df, !(x > 1))
filter(df, is.na(x) | x > 1)
```

```{r} 
filter(flights,arr_delay > 120) %>%
  select(month,day,arr_delay)
```

```{r}
filter(flights, dest %in% c("IAH","HOU"))
```


```{r}
filter(flights, dest == "IAH" | dest == "HOU") %>%
  select(month,day,flight, dest)
```
```{r}
filter(flights,between(month,7,9))
```

```{r}
filter(flights,!is.na(dep_delay),dep_delay <= 0, arr_delay > 120)
```
```{r}
filter(flights,!is.na(dep_delay),dep_delay >= 60, dep_delay-arr_delay > 30)
```

```{r}
filter(flights,between(dep_time,0,600))
```

```{r}
sum(is.na(flights$dep_time))
```
```{r}
filter(flights,is.na(dep_time))
```
```{r}
arrange(flights,desc(is.na(arr_delay)),arr_delay)
```
```{r}
arrange(flights,desc(distance))
```

```{r}
select(flights,dep_time,dep_delay,arr_time,arr_delay)
```
```{r}
select(flights,match("^(dep|arr)_time|delay)$"))
```

```{r}
select(flights,contains("TIME"))
```

```{r}
select(flights,one_of(c("year", "month", "day", "dep_delay", "arr_delay")))
```

```{r}
flights %>%
  select(one_of(c("year", "month", "day")))
```
```{r}
flights_sml <- select(flights, 
  year:day, 
  ends_with("delay"), 
  distance, 
  air_time
)
mutate(flights_sml,
  gain = arr_delay - dep_delay,
  speed = distance / air_time * 60
)
```

```{r}
mutate(flights_sml,
  gain = arr_delay - dep_delay,
  hours = air_time / 60,
  gain_per_hour = gain / hours
)
```

```{r}
transmute(flights,
  gain = arr_delay - dep_delay,
  hours = air_time / 60,
  gain_per_hour = gain / hours
)
```

```{r}
flights %>%
  filter(month == 11) %>%
  select(1:5) %>%
  mutate(
    dep_time = recode_time(dep_time),
    sched_dep_time = record_time(sched_dep_time)
  ) %>%
  group_by(day) %>%
  count()
```

```{r}
transmute(flights,
  dep_time,
  hour = dep_time %/% 100,
  minute = dep_time %% 100,
  numberofminute = hour * 60 + minute
)
```

```{r}
transmute(flights,
  air_time,
  arr_time,
  dep_time,
  fake = arr_time - dep_time,
  duration = fake %/% 100 * 60 + fake %% 100)
```

```{r}
min_rank(("arr_delay"))
```
```{r}
flights %>%
  group_by(year,month,day) %>%
  summarise(
    dep_delay = mean(dep_delay, na.rm = TRUE),
    arr_delay = mean(arr_delay, na.rm = TRUE),
    count = n(),
    count_nona = sum(!is.na(air_time))
  )
```

```{r}
not_canceled %>%
  group_by(tailnum) %>%
  summarize(
    delay = mean(arr_delay, na.rm = TRUE), 
    n= n()
  ) %>%
  filter(n > 50) %>%
  ggplot(data = delays, mapping = aex(x = n,y = delay))+
    geom_pint(alpha = 1/10) +
    geom_smooth(method = "ln")
```

```{r}
batters <- batting %>% 
  group_by(playerID) %>% 
  summarise(
    ba = sum(H, na.rm = TRUE) / sum(AB, na.rm = TRUE),
    ab = sum(AB, na.rm = TRUE)
  )

batters %>% 
  filter(ab > 100) %>% 
  ggplot(mapping = aes(x = ab, y = ba)) +
    geom_point() + 
    geom_smooth(se = FALSE)
```

```{r}
summarise(flights, delay = mean(dep_delay, na.rm = TRUE))
```

```{r}
by_day <- group_by(flights, year, month, day)
summarise(by_day, delay = mean(dep_delay, na.rm = TRUE))
```

```{r}
# by_dest <- group_by(flights, dest)
# delay <- summarise(by_dest,
#   count = n(),
#   dist = mean(distance, na.rm = TRUE),
#   delay = mean(arr_delay, na.rm = TRUE)
# )
# delay <- filter(delay, count > 20, dest != "HNL")

delays <- flights %>% 
  group_by(dest) %>% 
  summarise(
    count = n(),
    dist = mean(distance, na.rm = TRUE),
    delay = mean(arr_delay, na.rm = TRUE)
  ) %>% 
  filter(count > 20, dest != "HNL")
ggplot(data = delay, mapping = aes(x = dist, y = delay)) +
  geom_point(aes(size = count), alpha = 1/3) +
  geom_smooth(se = FALSE)
```

```{r}
not_canceled %>%
  group_by(tailnum) %>%
  summarise(
    n_late = sum(dep_delay > 10)
    n = n(),
    always_late = (min()arr_delay > 10)
  ) %>%
  filter(always_late) %>%
  arrange(desc(n))
not_canceled %>%
  filter(dep_delay < 15)
```

```{r}
not_canceled %>%
  group_by(tailnum) %>%
  summarise(
    n_early = sum(dep_delay <- 15),
    n = n(),
    prop_early = n_early / n
  ) %>%
  filter(prop_early >= 0.5)
```

```{r}
not_canceled %>%
  group_by(tailnum) %>%
  summarise(
    prop_on_time = mean(arr_delay <= 0),
    n = n()
  ) %>%
  arrange(desc(prop_on_time)) %>%
```

```{r}
not_canceled %>%
  count(tailnum, wt = distance) %>%
  arrange(desc(n))
not_canceled %>%
  group_by(tailnum) %>%
  summarise(
    distance = sum(distance)
  ) %>%
  arrange(desc(distance))
)
```

```{r}
ggplot(data = mpg) +
  geom_smooth(
    mapping = aes(x = displ, y = hwy, color = drv),
    show.legend = FALSE
  )
```


```{r}
N <- 1e6
U1 <- runif(N)
U2 <- runif(N)
mean(U2 ^ 2 > U2)
mean(runif(N) ^2 > runif(N))
```

